import './index.css'
import React from 'react';
import ReactDOM from 'react-dom/client';
import { RouterProvider, createRouter } from '@tanstack/react-router';

// Import the auto-generated route tree
import { routeTree } from './routeTree.gen'; // This file will be generated by the plugin!

// Create a new router instance
const router = createRouter({ routeTree });

// Register the router instance for type safety (IMPORTANT for TypeScript!)
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById('root');
if (!rootElement) throw new Error('Failed to find the root element');

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);