/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyTechniquesRouteImport } from './routes/study-techniques'
import { Route as StartRouteImport } from './routes/start'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyTechniquesFeynmannRouteImport } from './routes/study-techniques/feynmann'
import { Route as StudyTechniquesActiveRecallRouteImport } from './routes/study-techniques/active-recall'

const StudyTechniquesRoute = StudyTechniquesRouteImport.update({
  id: '/study-techniques',
  path: '/study-techniques',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyTechniquesFeynmannRoute = StudyTechniquesFeynmannRouteImport.update({
  id: '/feynmann',
  path: '/feynmann',
  getParentRoute: () => StudyTechniquesRoute,
} as any)
const StudyTechniquesActiveRecallRoute =
  StudyTechniquesActiveRecallRouteImport.update({
    id: '/active-recall',
    path: '/active-recall',
    getParentRoute: () => StudyTechniquesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/start': typeof StartRoute
  '/study-techniques': typeof StudyTechniquesRouteWithChildren
  '/study-techniques/active-recall': typeof StudyTechniquesActiveRecallRoute
  '/study-techniques/feynmann': typeof StudyTechniquesFeynmannRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/start': typeof StartRoute
  '/study-techniques': typeof StudyTechniquesRouteWithChildren
  '/study-techniques/active-recall': typeof StudyTechniquesActiveRecallRoute
  '/study-techniques/feynmann': typeof StudyTechniquesFeynmannRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/start': typeof StartRoute
  '/study-techniques': typeof StudyTechniquesRouteWithChildren
  '/study-techniques/active-recall': typeof StudyTechniquesActiveRecallRoute
  '/study-techniques/feynmann': typeof StudyTechniquesFeynmannRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/start'
    | '/study-techniques'
    | '/study-techniques/active-recall'
    | '/study-techniques/feynmann'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/start'
    | '/study-techniques'
    | '/study-techniques/active-recall'
    | '/study-techniques/feynmann'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/start'
    | '/study-techniques'
    | '/study-techniques/active-recall'
    | '/study-techniques/feynmann'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  StartRoute: typeof StartRoute
  StudyTechniquesRoute: typeof StudyTechniquesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-techniques': {
      id: '/study-techniques'
      path: '/study-techniques'
      fullPath: '/study-techniques'
      preLoaderRoute: typeof StudyTechniquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-techniques/feynmann': {
      id: '/study-techniques/feynmann'
      path: '/feynmann'
      fullPath: '/study-techniques/feynmann'
      preLoaderRoute: typeof StudyTechniquesFeynmannRouteImport
      parentRoute: typeof StudyTechniquesRoute
    }
    '/study-techniques/active-recall': {
      id: '/study-techniques/active-recall'
      path: '/active-recall'
      fullPath: '/study-techniques/active-recall'
      preLoaderRoute: typeof StudyTechniquesActiveRecallRouteImport
      parentRoute: typeof StudyTechniquesRoute
    }
  }
}

interface StudyTechniquesRouteChildren {
  StudyTechniquesActiveRecallRoute: typeof StudyTechniquesActiveRecallRoute
  StudyTechniquesFeynmannRoute: typeof StudyTechniquesFeynmannRoute
}

const StudyTechniquesRouteChildren: StudyTechniquesRouteChildren = {
  StudyTechniquesActiveRecallRoute: StudyTechniquesActiveRecallRoute,
  StudyTechniquesFeynmannRoute: StudyTechniquesFeynmannRoute,
}

const StudyTechniquesRouteWithChildren = StudyTechniquesRoute._addFileChildren(
  StudyTechniquesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  StartRoute: StartRoute,
  StudyTechniquesRoute: StudyTechniquesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
